MvcBlogApplication/MvcBlogApplication/Controllers/AdminController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using MvcBlog.Domain.Entities;
using System;
using System.Web;
using System.Drawing;
using MvcBlog.WebUI.Concrete;
using MvcBlog.WebUI.Infrastructure;
using MvcBlog.WebUI.Models;
using MvcBlog.WebUI.Tools;


namespace MvcBlog.WebUI.Controllers
{
    public class AdminController : BaseController
    {
        #region Posts
        //
        // GET: /Admin/ManagePosts

        [HttpGet]
        [Authorize(Roles = "Administrators")]
        public ActionResult ManagePosts()
        {
            ViewBag.CurrentEdit = "Posts";
            return View(Repository.Posts.OrderByDescending(p => p.PostID));
        }

        //
        // GET: /Admin/EditPost

        [HttpGet]
        [Authorize(Roles = "Administrators")]
        public ViewResult EditPost(int postId)
        {
            ViewBag.CurrentEdit = "Posts";
            var post = Repository.Posts.FirstOrDefault(p => p.PostID == postId);

            if (post != null)
            {

                ViewBag.Title = string.Format("Edit post '{0}'", post.PostTitle);

                return View(post);
            }
            return View("_NotFound");
        }

        //
        // POST: /Admin/EditPost

        [HttpPost]
        [Authorize(Roles = "Administrators")]
        [ValidateInput(false)]
        public ActionResult EditPost(Post post, HttpPostedFileBase postImage)
        {
            ViewBag.CurrentEdit = "Posts";
            if (ModelState.IsValid)
            {
                if (post.PostID == 0)
                {
                    post.PostCreatedBy = User.Identity.Name;
                    post.PostCreationDate = DateTime.Now;
                }

                post.PostLastModifiedBy = User.Identity.Name;
                post.PostLastModificationDate = DateTime.Now;

                if (postImage != null
                    && ImagesExtensions.SupportedFormat(postImage, SiteConfigService.AllowedImageTypes)
                    && ImagesExtensions.CheckSize(postImage, SiteConfigService.MaxImageSize))
                {
                    string prevImage = string.Empty;
                    if (!string.IsNullOrEmpty(post.ImageName))
                    {
                        // will be used to delete previous post images
                        prevImage = post.ImageName;
                    }

                    string imageExtension = Path.GetExtension(postImage.FileName);
                    string imageName = string.Format("{0}_{1}{2}", post.PostID, DateTime.Now.Ticks, imageExtension);
                    string imageThumbSavePath = Path.Combine(Server.MapPath(Url.Content("~/Content/")), SiteConfigService.PostThumbPath, imageName);
                    string imageFeaturedSavePath = Path.Combine(Server.MapPath(Url.Content("~/Content/")), SiteConfigService.PostFeaturedPath, imageName);

                    //image parameters
                    post.ImageMimeType = postImage.ContentType;
                    post.ImageName = imageName;

                    //resize proportional thumbnail image
                    Image.FromStream(postImage.InputStream)
                        .ResizeProportional(new Size(SiteConfigService.PostThumbImageWidth, SiteConfigService.PostThumbImageHeight))
                        .SaveToFolder(imageThumbSavePath);

                    //crop and resize featured image
                    Image.FromStream(postImage.InputStream)
                        .ResizeMinimalSqueeze(new Size(SiteConfigService.PostFeaturedImageWidth, SiteConfigService.PostFeaturedImageHeight))
                        .SaveToFolder(imageFeaturedSavePath);

                    // delete previous thumbnail picture if exists
                    if (!string.IsNullOrEmpty(prevImage) && System.IO.File.Exists(imageThumbSavePath))
                    {
                        System.IO.File.Delete(Path.Combine(Server.MapPath(Url.Content("~/Content/")), SiteConfigService.PostThumbPath, prevImage));
                    }

                    // delete previous featured image if exists
                    if (!string.IsNullOrEmpty(prevImage) && System.IO.File.Exists(imageFeaturedSavePath))
                    {
                        System.IO.File.Delete(Path.Combine(Server.MapPath(Url.Content("~/Content/")), SiteConfigService.PostFeaturedPath, prevImage));
                    }
                }

                // save updated data into DB
                Repository.SavePost(post);

                TempData["message"] = string.Format("{0} has been saved", post.PostTitle);
                return RedirectToAction("ManagePosts");
            }

            // something wrong occured with the data values
            return View(post);
        }

        //
        // GET: /Admin/CreatePost
        [HttpGet]
        [Authorize(Roles = "Administrators")]
        public ViewResult CreatePost()
        {
            ViewBag.Title = "Add new post";
            ViewBag.CurrentEdit = "Posts";
            return View("EditPost", new Post());
        }

        //
        // POST: /Admin/DeletePost

        [HttpGet]
        [Authorize(Roles = "Administrators")]
        public ActionResult DeletePost(int postId)
        {
            Post postToDelete = Repository.DeletePost(postId);

            // delete all images related to th post
            DeletePostImages(postToDelete);

            TempData["message"] = string.Format("{0} has been deleted", postToDelete.PostTitle);
            return RedirectToAction("ManagePosts");
        }

        #endregion

        #region Comments
        //
        // GET: /Admin/ManageComments
        [Authorize(Roles = "Administrators")]
        public ActionResult ManageComments()
        {
            ViewBag.CurrentEdit = "Comments";
            return View(Repository.Comments.OrderByDescending(c => c.CommentID));
        }

        //
        // GET: /Admin/EditComment
        [HttpGet]
        [Authorize(Roles = "Administrators")]
        public ViewResult EditComment(int commentId)
        {
            ViewBag.CurrentEdit = "Comments";
            var comment = Repository.Comments.FirstOrDefault(c => c.CommentID == commentId);
            return View(comment);
        }

        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public ActionResult EditComment(Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.CommentLastModifiedBy = User.Identity.Name;
                comment.CommentLastModificationDate = DateTime.Now;

                Repository.SaveComment(comment);

                TempData["message"] = string.Format("Comment (id = {0}) has been saved", comment.CommentID);
                return RedirectToAction("ManageComments");
            }

            // something wrong with the data values
            return View(comment);
        }

        [HttpGet]
        [Authorize(Roles = "Administrators")]
        public ActionResult DeleteComment(int commentId)
        {
            Repository.DeleteComment(commentId);

            TempData["message"] = string.Format("Comment (id = {0}) has been deleted.", commentId);

            return RedirectToAction("ManageComments");
        }

        #endregion

        #region Users
        [HttpGet]
        [Authorize(Roles = "Administrators")]
        public ActionResult ManageUsers()
        {
            ViewBag.CurrentEdit = "Users";

            var usList = new List<UserInRoleViewModel>();

            foreach (var user in Repository.UserProfiles)
            {
                usList.Add(new UserInRoleViewModel
                {
                    UserId = user.UserId,
                    UserName = user.UserName,
                    UserEmail = user.Email,
                    UserRole = Roles.GetRolesForUser(user.UserName).FirstOrDefault()
                });
            }

            return View(usList);
        }

        public ActionResult EditUser(int userId)
        {
            ViewBag.CurrentEdit = "Users";

            var user = new UserInRoleViewModel();
            var dbRow = Repository.UserProfiles.FirstOrDefault(u => u.UserId == userId);

            if (dbRow != null)
            {
                user.UserId = userId;
                user.UserName = dbRow.UserName;
                user.UserEmail = dbRow.Email;
                user.UserRole = Roles.GetRolesForUser(dbRow.UserName).FirstOrDefault();

                var roles = new List<string>();

                foreach (var role in Roles.GetAllRoles())
                {
                    roles.Add(role);
                }

                user.AvailableRoles = roles;
            }
            return View(user);
        }

        [HttpPost]
        public ActionResult EditUser(UserInRoleViewModel user)
        {
            ViewBag.CurrentEdit = "Users";

            if (Roles.GetRolesForUser(user.UserName).Any())
            {
                Roles.RemoveUserFromRoles(user.UserName, Roles.GetRolesForUser(user.UserName));
            }

            if (user.UserRole != "None")
            {

                Roles.AddUserToRole(user.UserName, user.UserRole);
            }

            return RedirectToAction("ManageUsers");
        }

        #endregion

        #region roles
        public ActionResult ManageRoles()
        {
            ViewBag.CurrentEdit = "Roles";

            var roles = new List<RoleViewModel>();

            foreach (string s in Roles.GetAllRoles())
            {
                roles.Add(new RoleViewModel { RoleName = s });
            }

            return View(roles);
        }

        public ActionResult DeleteRole(string roleName)
        {
            if (Roles.RoleExists(roleName))
            {
                Roles.RemoveUsersFromRole(Roles.GetUsersInRole(roleName), roleName);
                Roles.DeleteRole(roleName);

MvcBlogApplication/MvcBlogApplication/Controllers/NavigationController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MvcBlog.Domain;

namespace MvcBlog.WebUI.Controllers
{
    public class NavigationController : Controller
    {
        private readonly IRepository _repository;

        public NavigationController(IRepository repository)
        {
            _repository = repository;
        }


        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = _repository.Posts
                .Where(p => p.PostIsVisible == true)
                .Select(p => p.PostCategory)
                .Distinct()
                .OrderBy(x => x).ToList();

            return PartialView(categories);
        }

    }
}

MvcBlogApplication/MvcBlogApplication/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" />

    @Styles.Render("~/Content/admincss")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <title>MVC Blog: @ViewBag.Title</title>

</head>
<body>

    <div id="admin-tabs">
        @Html.ActionLink("Back to site", "List", "Posts")
        @Html.ActionLink("Manage posts", "ManagePosts", "Admin", new { @class = @ViewBag.CurrentEdit == "Posts" ? "selected-posts" : null })
        @Html.ActionLink("Manage comments", "ManageComments", "Admin", new { @class = @ViewBag.CurrentEdit == "Comments" ? "selected-comments" : null })
        @Html.ActionLink("Manage users", "ManageUsers", "Admin", new { @class = @ViewBag.CurrentEdit == "Users" ? "selected-users" : null })
        @Html.ActionLink("Manage roles", "ManageRoles", "Admin", new { @class = @ViewBag.CurrentEdit == "Roles" ? "selected-roles" : null })
        @Html.ActionLink("Site configuration", "SiteConfig", "Admin", new { @class = @ViewBag.CurrentEdit == "Site" ? "selected-site" : null })
    </div>

    @if (TempData["message"] != null)
    {
        <div id="info-message" class="alert message-container">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            @TempData["message"]
        </div>
    }

    @RenderBody()
</body>
</html>

@RenderSection("scripts", required: false)

MvcBlogApplication/MvcBlogApplication/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

MvcBlogApplication/MvcBlogApplication/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

MvcBlogApplication/MvcBlogApplication/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>MVC Blog: @ViewBag.Title</title>
    <meta name="viewport" content="width=device-width" />

    @Styles.Render("~/Content/sitecss")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryAjax")
    @Scripts.Render("~/bundles/bootstrap")

    <script type="text/javascript">
        $(document).ready(function () {

            $(window).scroll(function () {
                if ($(this).scrollTop() > 100) {
                    $('.scrollup').fadeIn();
                } else {
                    $('.scrollup').fadeOut();
                }
            });

            $('.scrollup').click(function () {
                $("html, body").animate({ scrollTop: 0 }, 600);
                return false;
            });

        });
    </script>

</head>

<body class="body-layout">
    <div style="background-color: white">
        <div id="header">
            <div id="header-title">
                <a href="@Url.Action("List", "Posts", routeValues: new { page = 1 })">ASP.NET MVC Blog</a>
            </div>
            <div id="login">
                @Html.Partial("~/Views/Shared/_LoginPartial.cshtml")
            </div>
        </div>
        <div id="categories">
            <p>
                @{ Html.RenderAction("Menu", "Navigation"); }
            </p>
        </div>
        <div id="content">
            @RenderBody()
        </div>

        <div id="footer">
            <div>
                <p>&copy; @DateTime.Now.Year - MVC Blog Application</p>
            </div>
        </div>
        <a href="#" class="scrollup"> Scroll</a>
    </div>
</body>
</html>

@RenderSection("scripts", required: false)
@RenderSection("styles", required: false)

MvcBlogApplication/MvcBlogApplication/Views/Shared/_NotFound.cshtml
@{
    ViewBag.Title = "MVC Blog: Page not found";
}

<h2></h2>
Oops! There is no page you are looking for...

MvcBlogApplication/MvcBlogApplication/Views/Shared/_PostSummary.cshtml
@model MvcBlog.Domain.Entities.Post

<div id="post">

    <h4>@Model.PostTitle</h4>
    <p>
        Posted @Model.PostCreationDate by @Model.PostCreatedBy in @Html.RouteLink(@Model.PostCategory, new { controller = "Posts", action = "List", category = @Model.PostCategory, page = 1 }) category
    </p>

    @if (Model.ImageName != null)
    {

        <div class="summary-image">
            <img width="300"
             height="200"
             src="@Url.Action("GetPostThumbnail", "Posts", new { Model.PostID })"
             alt="Image for post '@Model.PostTitle'"
             title="@Model.PostTitle" />
        </div>
    }

    <div class="summary-text">
        @Html.Raw(@Model.PostDescription)
    </div>
</div>

<div id="detailedLink">
    @Html.PostDetailsLinks(@Model.PostID, x => Url.Action(actionName: "SinglePost", controllerName: "Posts", routeValues: new { postId = x, category = Model.PostCategory }))
</div>