MvcBlogApplication/MvcBlogApplication/Controllers/FeaturedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBlog.Domain;

namespace MvcBlog.WebUI.Controllers
{
    public class FeaturedController : Controller
    {
        private readonly IRepository _repository;

        public FeaturedController(IRepository repository)
        {
            _repository = repository;
        }

        //
        // GET: 

        public PartialViewResult Slides()
        {
            var featuredPosts = _repository.Posts
                .Where(p => p.PostFeatured == true && p.PostIsVisible == true)
                .OrderByDescending(p => p.PostID);

            return PartialView(featuredPosts);
        }
    }
}

MvcBlogApplication/MvcBlogApplication/Controllers/PostsController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web.Mvc;
using MvcBlog.Domain;
using MvcBlog.Domain.Entities;
using MvcBlog.WebUI.Models;
using System.Configuration;
using System;
using System.IO;
using MvcBlog.WebUI.Concrete;
using MvcBlog.WebUI.Abstract;

namespace MvcBlog.WebUI.Controllers
{
    public class PostsController : BaseController
    {
        //
        // POST: /Posts/
        // List posts
        public ViewResult List(string category, int page = 1)
        {
            var model = new PostsListViewModel
            {
                Posts = Repository.Posts
                .Where(p => category == null && p.PostIsVisible == true
                    || p.PostCategory == category && p.PostIsVisible == true)
                .OrderByDescending(p => p.PostID)
                .Skip((page - 1) * SiteConfigService.PostsPerPage)
                .Take(SiteConfigService.PostsPerPage),

                PagingModel = new PagingModel
                {
                    CurrentPage = page,
                    ItemsPerPage = SiteConfigService.PostsPerPage,
                    TotalItems = category == null ? Repository.Posts.Count() : Repository.Posts.Count(p => p.PostCategory == category)
                }
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult SinglePost(int postId)
        {
            Post detailed = Repository.Posts.FirstOrDefault(p => p.PostID == postId && p.PostIsVisible == true);

            return View(detailed);
        }

        [HttpGet]
        public PartialViewResult CommentsList(int postId)
        {
            var commentsList = Repository.Comments
                .Where(c => c.PostID == postId && c.CommentIsVisible)
                .OrderBy(p=>p.CommentID);

            return PartialView(commentsList);
        }

        [HttpGet]
        [Authorize]
        public PartialViewResult AddComment(int postId)
        {
            var comment = new Comment {PostID = postId};

            return PartialView(comment);
        }

        [Authorize]
        [ValidateInput(false)]
        public ActionResult AddComment(Comment comment)
        {
            comment.CommentCreatedBy = User.Identity.Name;
            comment.CommentCreationDate = DateTime.Now;
            comment.CommentLastModifiedBy = User.Identity.Name;
            comment.CommentLastModificationDate = DateTime.Now;
            comment.CommentIsVisible = true;

            Repository.SaveComment(comment);
            return RedirectToAction("CommentsList", routeValues: new { postId = comment.PostID });
        }

        // get thumbnail image for the post
        public FilePathResult GetPostThumbnail(int postId)
        {
            Post post = Repository.Posts.FirstOrDefault(p => p.PostID == postId);
            if (post != null)
            {
                return File(Path.Combine(Server.MapPath(Url.Content("~/Content/")), SiteConfigService.PostThumbPath ,post.ImageName), post.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        // get featured image for the post
        public FilePathResult GetPostFeatured(int postId)
        {
            Post post = Repository.Posts.FirstOrDefault(p => p.PostID == postId);
            if (post != null)
            {
                return File(Path.Combine(Server.MapPath(Url.Content("~/Content/")), SiteConfigService.PostFeaturedPath, post.ImageName), post.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

MvcBlogApplication/MvcBlogApplication/Views/Posts/AddComment.cshtml
@model MvcBlog.Domain.Entities.Comment

<script>
    function OnSuccess() {
        document.getElementById('submitForm').reset();
    }
</script>


@using (Ajax.BeginForm("AddComment", "Posts", new AjaxOptions()
{
    UpdateTargetId = "commentsList",
    InsertionMode = InsertionMode.Replace,
    OnSuccess = "OnSuccess"
}, htmlAttributes: new { @id = "submitForm" }))
{
    @Html.TextAreaFor(p => p.CommentContent)
    @Html.Hidden("postId", @Model.PostID)

    <input type="submit" value="Save Comment" class="submit-comment" />
}

MvcBlogApplication/MvcBlogApplication/Views/Posts/CommentsList.cshtml
@model IEnumerable<MvcBlog.Domain.Entities.Comment>
           
<div id="comments-list">
    @foreach (var c in Model)
    {
        <div class="comment item">

            <h3>@c.CommentCreationDate @c.CommentCreatedBy said:</h3>
            <div class="comment-avatar">
                <img src="@Url.Action("GetUserAvatar", "Account", new { userName = c.CommentCreatedBy })" height="90" width="90" />
            </div>
            <div class="comment-text">
                <p class="multiline">@Html.Raw(@c.CommentContent)</p>
            </div>
            <p style="clear: left"></p>
        </div>
    }
</div>

MvcBlogApplication/MvcBlogApplication/Views/Posts/List.cshtml
@using MvcBlog.WebUI.HtmlHelpers

@model MvcBlog.WebUI.Models.PostsListViewModel

@{
    ViewBag.Title = "Posts";
}


@{ Html.RenderAction("Slides", "Featured"); }

@foreach (var p in Model.Posts)
{
    @Html.Partial("~/Views/Shared/_PostSummary.cshtml", p);
}

<div id="pagination">
    @Html.PageLinks(Model.PagingModel, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

MvcBlogApplication/MvcBlogApplication/Views/Posts/SinglePost.cshtml
@model MvcBlog.Domain.Entities.Post

@{
    ViewBag.Title = "\"" + @Model.PostTitle + "\"";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--Initialize TinyMCE wysiwyg redactor-->
<script src="~/Scripts/tinymce/tinymce.min.js"></script>
<script>
    tinymce.init({
        selector: "textarea",
        menubar: false,
        statusbar: true,
        resize: true,
        toolbar: "undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent"
    });

</script>

<div class="item">
    <h2>@Model.PostTitle</h2>
</div>

<p>
    Created @Model.PostCreationDate by <strong>@Model.PostCreatedBy</strong> |
    Last modified @Model.PostLastModificationDate by <strong>@Model.PostLastModifiedBy</strong>
</p>

<div class="item">
    <p>In category: <strong>"@Model.PostCategory"</strong></p>
</div>

<div class="multiline">
    @Html.Raw(@Model.PostContent)
</div>
<hr />

<!--Social-->
<ul class="social-likes">
    <li class="facebook" title="Share link on Facebook">Facebook</li>
    <li class="twitter" title="Share link on Twitter">Twitter</li>
    <li class="plusone" title="Share link on Google+">Google+</li>
</ul>

<div class="item">
    <h4>Comments:</h4>
</div>

<div id="commentsList">
    @Html.Action("CommentsList")
</div>

@if (@Model.PostCommentsEnabled)
{
    if (User.Identity.IsAuthenticated)
    {
        @Html.Action("AddComment")
    }

    else
    {
        <text>Only authorized users can left comments. Please </text>
        @Html.ActionLink("authorize.", "Login", "Account", htmlAttributes: null, routeValues: new { returnUrl = Request.RawUrl })
    }
}
else
{
    <div>
        Sorry. Comments are disabled for this post!
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/socialLikes")
}

@section Styles {
    @Styles.Render("~/Content/socialcss")
}